In [ ]:
import pandas as pd
data=pd.read_csv("/content/car_price_dataset.csv")
print(data["Brand"].unique())
print(data[data["Brand"]=="Toyota"])

['Kia' 'Chevrolet' 'Mercedes' 'Audi' 'Volkswagen' 'Toyota' 'Honda' 'BMW'
 'Hyundai' 'Ford']
       Brand    Model  Year  Engine_Size Fuel_Type    Transmission  Mileage  \
5     Toyota    Camry  2007          2.7    Petrol       Automatic   157889
9     Toyota     RAV4  2005          3.1    Petrol          Manual   107724
21    Toyota     RAV4  2000          4.6    Hybrid  Semi-Automatic    41814
22    Toyota     RAV4  2003          2.0  Electric          Manual   136662
34    Toyota  Corolla  2010          3.2    Diesel       Automatic   132454
...      ...      ...   ...          ...       ...             ...      ...
9946  Toyota     RAV4  2000          2.0    Petrol  Semi-Automatic    61667
9959  Toyota  Corolla  2006          3.8    Petrol          Manual   138450
9965  Toyota    Camry  2017          5.0  Electric          Manual   150119
9975  Toyota  Corolla  2015          4.7    Petrol       Automatic   123316
9989  Toyota  Corolla  2003          1.6    Diesel  Semi-Automatic   205647

      Doors  Owner_Count  Price
5         4            4   7242
9         2            5   6545
21        2            2   8863
22        5            4   6266
34        4            4   9150
...     ...          ...    ...
9946      3            5   4866
9959      4            3   6931
9965      4            1  13197
9975      3            2  12333
9989      4            4   2487

[970 rows x 10 columns]

In [ ]:
data["Fuel_Type"].unique()

array(['Diesel', 'Hybrid', 'Electric', 'Petrol'], dtype=object)

In [ ]:
data[data["Fuel_Type"]=="Diesel"]

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
0,Kia,Rio,2020,4.2,Diesel,Manual,289944,3,5,8501
2,Mercedes,GLA,2020,4.2,Diesel,Automatic,231440,4,2,11171
15,Volkswagen,Golf,2007,3.2,Diesel,Automatic,60103,2,1,9697
18,Kia,Rio,2000,3.4,Diesel,Semi-Automatic,257427,3,3,2351
25,Kia,Sportage,2011,1.8,Diesel,Automatic,92188,2,4,8856
...,...,...,...,...,...,...,...,...,...,...
9988,BMW,3 Series,2010,3.0,Diesel,Manual,105615,4,2,7987
9989,Toyota,Corolla,2003,1.6,Diesel,Semi-Automatic,205647,4,4,2487
9991,Mercedes,E-Class,2017,1.1,Diesel,Automatic,179286,5,1,8214
9995,Kia,Optima,2004,3.7,Diesel,Semi-Automatic,5794,2,4,8884
9999,Volkswagen,Tiguan,2001,2.1,Diesel,Manual,157882,3,3,3342

In [ ]:
data["Transmission"].unique()

array(['Manual', 'Automatic', 'Semi-Automatic'], dtype=object)

In [ ]:
data["Transmission"]=="Automatic"

0       False
1        True
2        True
3       False
4       False
        ...
9995    False
9996     True
9997     True
9998     True
9999    False
Name: Transmission, Length: 10000, dtype: bool

In [ ]:
data['Year'] = data['Year'].astype(str)

In [ ]:
data[data["Year"]=="2015"]

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
53,Honda,Civic,2015,2.6,Electric,Semi-Automatic,66777,5,1,11864
62,Ford,Focus,2015,4.8,Electric,Automatic,100603,4,2,14887
84,Hyundai,Tucson,2015,1.6,Electric,Manual,259533,2,4,7009
85,Mercedes,C-Class,2015,4.1,Petrol,Automatic,197249,3,1,10255
130,Volkswagen,Passat,2015,4.7,Diesel,Manual,220366,5,1,8892
...,...,...,...,...,...,...,...,...,...,...
9881,Chevrolet,Malibu,2015,2.5,Diesel,Automatic,228993,2,3,8020
9883,BMW,5 Series,2015,4.9,Diesel,Manual,28128,2,4,12937
9937,Mercedes,GLA,2015,2.6,Diesel,Automatic,187667,2,1,8946
9952,Mercedes,GLA,2015,4.9,Electric,Automatic,14529,2,5,16709
9975,Toyota,Corolla,2015,4.7,Petrol,Automatic,123316,3,2,12333

In [ ]:
data[data["Price"]<10000]

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
0,Kia,Rio,2020,4.2,Diesel,Manual,289944,3,5,8501
4,Volkswagen,Golf,2003,2.6,Hybrid,Semi-Automatic,286618,3,3,2867
5,Toyota,Camry,2007,2.7,Petrol,Automatic,157889,4,4,7242
7,Kia,Sportage,2001,4.7,Electric,Semi-Automatic,157495,2,2,7950
8,Kia,Sportage,2014,2.6,Hybrid,Manual,98700,3,4,9926
...,...,...,...,...,...,...,...,...,...,...
9995,Kia,Optima,2004,3.7,Diesel,Semi-Automatic,5794,2,4,8884
9996,Chevrolet,Impala,2002,1.4,Electric,Automatic,168000,2,1,6240
9997,BMW,3 Series,2010,3.0,Petrol,Automatic,86664,5,1,9866
9998,Ford,Explorer,2002,1.4,Hybrid,Automatic,225772,4,1,4084
9999,Volkswagen,Tiguan,2001,2.1,Diesel,Manual,157882,3,3,3342

In [ ]:
data[data['Mileage']<50000]

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
1,Chevrolet,Malibu,2012,2.0,Hybrid,Automatic,5356,2,3,12092
11,Volkswagen,Golf,2009,4.5,Hybrid,Manual,42795,4,3,11444
16,Hyundai,Elantra,2017,2.9,Electric,Automatic,38133,5,2,14837
17,Volkswagen,Tiguan,2006,4.5,Electric,Manual,41161,2,2,11576
19,Mercedes,GLA,2021,1.5,Petrol,Manual,34640,2,1,11207
...,...,...,...,...,...,...,...,...,...,...
9974,Mercedes,C-Class,2020,1.1,Diesel,Manual,16669,5,1,10866
9980,Honda,CR-V,2012,1.5,Petrol,Manual,37233,3,2,8455
9987,BMW,5 Series,2004,1.3,Diesel,Manual,19392,2,2,6212
9992,BMW,5 Series,2016,1.2,Hybrid,Automatic,13386,3,5,12332
9995,Kia,Optima,2004,3.7,Diesel,Semi-Automatic,5794,2,4,8884

In [ ]:
data[data['Model']=='Suv']

Empty DataFrame
Columns: [Brand, Model, Year, Engine_Size, Fuel_Type, Transmission, Mileage, Doors, Owner_Count, Price]
Index: []